{
 "title": "Python App Observability",
 "tags": [
  "python",
  "prometheus",
  "observability"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "process_open_fds", "legendFormat": "FDs" }
   ]
  },
  {
   "title": "Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    { "expr": "avg(app_request_count_total)", "legendFormat": "Requests/sec" }
   ]
  },
  {
   "title": "Request Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(app_request_processing_seconds_sum[1m]) / rate(app_request_processing_seconds_count[1m])",
     "legendFormat": "Latency (avg sec)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 14 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "RSS" }
   ]
  }
 ]
}